package shame.nazuna.api.storages.implement.helpertstorages.enumvar;
 import shame.nazuna.client.modules.impl.combat.ElytraResolver;
 import shame.nazuna.client.modules.impl.combat.TriggerBot;
 import shame.nazuna.client.modules.impl.misc.LeaveTracker;
 import shame.nazuna.client.modules.impl.player.AutoForest;
 import shame.nazuna.client.modules.impl.player.ChestStealer;
 import shame.nazuna.client.modules.impl.render.LineGlyphes;
 import shame.nazuna.client.modules.impl.render.Particle;
 import shame.nazuna.client.modules.impl.render.ShulkerPreview;
 
 public interface ModuleRewords {
   public static final AirStuck airStuck = AirStuck.INSTANCE;
   public static final Arrows arrows = Arrows.INSTANCE;
   public static final Aura aura = Aura.INSTANCE;
   public static final AntiBot antibot = AntiBot.INSTANCE;
   public static final AutoAccept autoAccept = AutoAccept.INSTANCE;
   public static final AutoArmor autoArmor = AutoArmor.INSTANCE;
   public static final AutoFish autoFish = AutoFish.INSTANCE;
   public static final AutoForest autoForest = AutoForest.INSTANCE;
   public static final DeathCoord deathCoord = DeathCoord.INSTANCE;
   public static final LeaveTracker leavetracker = LeaveTracker.INSTANCE;
   public static final EcOpen ecopen = EcOpen.INSTANCE;
   public static final AutoBuy autoBuy = AutoBuy.INSTANCE;
   public static final AutoDuel autoDuel = AutoDuel.INSTANCE;
   public static final AutoEat autoEat = AutoEat.INSTANCE;
   public static final AutoLeave autoLeave = AutoLeave.INSTANCE;
   public static final AutoExplosion autoExplosion = AutoExplosion.INSTANCE;
   public static final AutoJoin autoJoin = AutoJoin.INSTANCE;
   public static final AutoPvp autoPvp = AutoPvp.INSTANCE;
   public static final NameProtect nameProtect = NameProtect.INSTANCE;
   public static final AutoJump autoJump = AutoJump.INSTANCE;
   public static final ChestStealer chestStealer = ChestStealer.INSTANCE;
   public static final ClientSounds clientSounds = ClientSounds.INSTANCE;
   public static final AutoTool autoTool = AutoTool.INSTANCE;
   public static final AutoTotem autoTotem = AutoTotem.INSTANCE;
   public static final AutoTrap autoTrap = AutoTrap.INSTANCE;
   public static final BlockOverlay blockOverlay = BlockOverlay.INSTANCE;
   public static final ClickPearl clickPearl = ClickPearl.INSTANCE;
   public static final Cosmetics cosmetics = Cosmetics.INSTANCE;
   public static final Cubes cubes = Cubes.INSTANCE;
   public static final KillEffect killEffect = KillEffect.INSTANCE;
   public static final BlockESP blockesp = BlockESP.INSTANCE;
   public static final ElytraBoost elytraBoost = ElytraBoost.INSTANCE;
   public static final ElytraMotion elytraMotion = ElytraMotion.INSTANCE;
   public static final ElytraSwap elytraSwap = ElytraSwap.INSTANCE;
   public static final ElytraTarget elytraTarget = ElytraTarget.INSTANCE;
   public static final ElytraResolver elytraresolver = ElytraResolver.INSTANCE;
   public static final EntityESP entityESP = EntityESP.INSTANCE;
   public static final Flight flight = Flight.INSTANCE;
   public static final FreeCam freeCam = FreeCam.INSTANCE;
   public static final FullBright fullBright = FullBright.INSTANCE;
   public static final GrimNoFall grimNoFall = GrimNoFall.INSTANCE;
   public static final GrimGlide grimGlide = GrimGlide.INSTANCE;
   public static final HighJump highJump = HighJump.INSTANCE;
   public static final HelpMessage helpMessage = HelpMessage.INSTANCE;
   public static final HitBubbles hitBubbles = HitBubbles.INSTANCE;
   public static final Interface interfaceModule = Interface.INSTANCE;
   public static final InterpolateF5 interpolateF5 = InterpolateF5.INSTANCE;
   public static final InventoryWalk inventoryWalk = InventoryWalk.INSTANCE;
   public static final ItemAim itemAim = ItemAim.INSTANCE;
   public static final ItemScroller itemScroller = ItemScroller.INSTANCE;
   public static final ItemRelease itemRelease = ItemRelease.INSTANCE;
   public static final JumpCircle jumpCircle = JumpCircle.INSTANCE;
   public static final KTLeave kTLeave = KTLeave.INSTANCE;
   public static final LineGlyphes lineGlyphes = LineGlyphes.INSTANCE;
   public static final LockSlot lockSlot = LockSlot.INSTANCE;
   public static final NoClip noClip = NoClip.INSTANCE;
   public static final NoJumpDelay noJumpDelay = NoJumpDelay.INSTANCE;
   public static final Nuker nuker = Nuker.INSTANCE;
   public static final NoPush noPush = NoPush.INSTANCE;
   public static final NoVelocity noVelocity = NoVelocity.INSTANCE;
   public static final NoVignette noVignette = NoVignette.INSTANCE;
   public static final NoControllerWeb noControllerWeb = NoControllerWeb.INSTANCE;
   public static final NoWeb noWeb = NoWeb.INSTANCE;
   public static final PacketCriticals packetCriticals = PacketCriticals.INSTANCE;
   public static final Particle particle = Particle.INSTANCE;
   public static final PlayerFakeLags playerFakeLags = PlayerFakeLags.INSTANCE;
   public static final Projectile projectile = Projectile.INSTANCE;
   public static final FireworkESP fireworkESP = FireworkESP.INSTANCE;
   public static final FastBreak fastBreak = FastBreak.INSTANCE;
   public static final FastExp fastExp = FastExp.INSTANCE;
   public static final Removals removals = Removals.INSTANCE;
   public static final RPSpoofer rPSpoofer = RPSpoofer.INSTANCE;
   public static final SeeInvisibles seeInvisibles = SeeInvisibles.INSTANCE;
   public static final ShaderEsp shaderEsp = ShaderEsp.INSTANCE;
   public static final ShaderHands shaderHands = ShaderHands.INSTANCE;
   public static final Satellite sattelite = Satellite.INSTANCE;
   public static final ShulkerPreview shulkerPreview = ShulkerPreview.INSTANCE;
   public static final Sonar sonar = Sonar.INSTANCE;
   public static final Speed speed = Speed.INSTANCE;
   public static final Sprint sprint = Sprint.INSTANCE;
   public static final SwingAnimations swingAnimations = SwingAnimations.INSTANCE;
   public static final TargetESP targetESP = TargetESP.INSTANCE;
   public static final TargetPearl targetPearl = TargetPearl.INSTANCE;
   public static final Timer timer = Timer.INSTANCE;
   public static final TotemAngel totemAngel = TotemAngel.INSTANCE;
   public static final TpBack tpBack = TpBack.INSTANCE;
   public static final TpsSync tpsSync = TpsSync.INSTANCE;
   public static final TpLoot tpLoot = TpLoot.INSTANCE;
   public static final ViewModel viewModel = ViewModel.INSTANCE;
   public static final WorldTweaks worldTweaks = WorldTweaks.INSTANCE;
   public static final XCarry xCarry = XCarry.INSTANCE;
   public static final AutoSwap autoSwap = AutoSwap.INSTANCE;
   public static final AimBot aimBot = AimBot.INSTANCE;
   public static final TriggerBot triggerBot = TriggerBot.INSTANCE;
   public static final NoSlow noSlow = NoSlow.INSTANCE;
   public static final ScoreboardHP scoreboardHP = ScoreboardHP.INSTANCE;
   public static final Step step = Step.INSTANCE;
   public static final ServerHelper serverHelper = ServerHelper.INSTANCE;
   public static final Spider spider = Spider.INSTANCE;
   public static final LootTracker lootTracker = LootTracker.INSTANCE;
   public static final HitMarker hitMarker = HitMarker.INSTANCE;
   public static final Trails trails = Trails.INSTANCE;
   public static final Trajectories trajectories = Trajectories.INSTANCE;
 }

